FROM python:3.9-alpine
 
# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
 
# Set the working directory
WORKDIR /app
 
# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
 
# Copy the application files
COPY . /app
 
# Expose port 5000
EXPOSE 5000
 
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
# Run the application
#CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
ENTRYPOINT [ "/entrypoint.sh" ]